from __future__ import annotations

import shutil
from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from typing import Any

from .activity_log import ActivityLog
from .artifacts import ArtifactManager
from .models import ActionResult, Artifact, PlanStep
from .util import new_id


class ActionExecutor:
    def __init__(self, activity_log: ActivityLog, artifacts: ArtifactManager) -> None:
        self._log = activity_log
        self._artifacts = artifacts

    def execute_step(self, step: PlanStep, context: dict[str, Any]) -> tuple[ActionResult, list[Artifact]]:
        self._log.write("step_started", {"step_id": step.step_id, "kind": step.kind, "title": step.title})
        try:
            result, artifacts = self._execute(step, context)
        except Exception as e:
            result = ActionResult(step_id=step.step_id, ok=False, message=str(e))
            artifacts = []
        self._log.write("step_completed", {"result": asdict(result)})
        for a in artifacts:
            self._log.write("artifact_created", asdict(a))
        return result, artifacts

    def _execute(self, step: PlanStep, context: dict[str, Any]) -> tuple[ActionResult, list[Artifact]]:
        kind = step.kind
        if kind == "conversation.clarify":
            return (
                ActionResult(step_id=step.step_id, ok=False, message=step.payload["question"]),
                [],
            )
        if kind == "fs.scan":
            root = Path(step.payload["root"])
            files = sorted([p.name for p in root.iterdir() if p.is_file()])
            context["fs.files"] = files
            return ActionResult(step_id=step.step_id, ok=True, message=f"Found {len(files)} files.", data={"files": files}), []
        if kind == "fs.preview_cleanup":
            root = Path(step.payload["root"])
            ops = _propose_cleanup_ops(root)
            context["fs.cleanup_ops"] = ops
            return (
                ActionResult(
                    step_id=step.step_id,
                    ok=True,
                    message=f"Previewed {len(ops)} operations.",
                    data={"operations": ops},
                ),
                [],
            )
        if kind == "fs.apply_cleanup":
            root = Path(step.payload["root"])
            ops = context.get("fs.cleanup_ops", [])
            applied = _apply_ops(root, ops)
            return (
                ActionResult(
                    step_id=step.step_id,
                    ok=True,
                    message=f"Applied {applied} operations.",
                    data={"applied": applied},
                ),
                [],
            )
        if kind == "browser.list_tabs":
            tabs = [
                {"title": "Example 1", "url": "https://example.com/1"},
                {"title": "Example 2", "url": "https://example.com/2"},
            ]
            context["browser.tabs"] = tabs
            return ActionResult(step_id=step.step_id, ok=True, message=f"Found {len(tabs)} tabs (stub).", data={"tabs": tabs}), []
        if kind == "browser.read_form":
            schema = {"fields": [{"name": "full_name", "type": "text"}, {"name": "email", "type": "email"}]}
            context["browser.form_schema"] = schema
            return ActionResult(step_id=step.step_id, ok=True, message="Read form schema (stub).", data=schema), []
        if kind == "browser.fill_form":
            schema = context.get("browser.form_schema") or {"fields": []}
            return ActionResult(step_id=step.step_id, ok=True, message=f"Filled {len(schema['fields'])} fields (stub)."), []
        if kind == "browser.stop_before_submit":
            return ActionResult(step_id=step.step_id, ok=True, message="Stopped before submit. Ready for explicit approval to submit."), []
        if kind == "artifact.write_markdown":
            tabs = context.get("browser.tabs", [])
            sources = "\n".join([f"- {t['title']} ({t['url']})" for t in tabs]) or "- (no sources selected)"
            summary = "This is a placeholder summary generated by the skeleton."
            template = step.payload["template"]
            content = template.format(sources=sources, summary=summary)
            artifact = self._artifacts.create_markdown(title=step.payload["title"], content=content)
            return ActionResult(step_id=step.step_id, ok=True, message=f"Created artifact: {artifact.title}", data={"path": artifact.path}), [artifact]
        return ActionResult(step_id=step.step_id, ok=False, message=f"Unknown step kind: {kind}"), []


def _is_probably_invoice(name: str) -> bool:
    n = name.lower()
    return "invoice" in n or n.startswith("inv_") or n.startswith("invoice_")


def _is_probably_screenshot(name: str) -> bool:
    n = name.lower()
    return n.startswith("screenshot") or n.startswith("screen shot") or n.startswith("screen_shot")


def _month_bucket_for(path: Path) -> str:
    dt = datetime.fromtimestamp(path.stat().st_mtime)
    return f"{dt.year:04d}-{dt.month:02d}"


def _propose_cleanup_ops(root: Path) -> list[dict[str, str]]:
    ops: list[dict[str, str]] = []
    for p in root.iterdir():
        if not p.is_file():
            continue
        if _is_probably_invoice(p.name):
            dst_dir = root / "Invoices"
            dst = dst_dir / p.name
            if dst.resolve() != p.resolve():
                ops.append({"op": "move", "src": str(p), "dst": str(dst)})
            continue
        if _is_probably_screenshot(p.name):
            bucket = _month_bucket_for(p)
            dst_dir = root / "Screenshots" / bucket
            dst = dst_dir / p.name
            if dst.resolve() != p.resolve():
                ops.append({"op": "move", "src": str(p), "dst": str(dst)})
    return ops


def _apply_ops(root: Path, ops: list[dict[str, str]]) -> int:
    applied = 0
    root = root.resolve()
    for op in ops:
        if op.get("op") != "move":
            continue
        src = Path(op["src"]).resolve()
        dst = Path(op["dst"]).resolve()
        if root not in src.parents:
            continue
        if root not in dst.parents:
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        if dst.exists():
            dst = dst.parent / f"{dst.stem}_{new_id('dup')}{dst.suffix}"
        shutil.move(str(src), str(dst))
        applied += 1
    return applied
